### ISSUE TITLE
howto

### ISSUE THREAD

**Issue by ghost** [vsimkus/voice-conversion#1]
is there doc somewhere on what it does and how?

**Comment by vsimkus** [comment]
Hi, I will add a how-to on running it in a few weeks when I get some free time. 

The main goal of the project was to compare the three different latent representations in modelling speech data for voice conversion. (I may later add the final report of our research after discussing with my team). Note that the project was not intended for production systems as of now. Due to limited compute in our research we have limited the comparison to simple convolutional nets, which are rather suboptimal. To achieve results closer to the state-of-the-art you would need to replace the transpose-convolutional decoder with something more powerful, such as a WaveNet for example.

**Comment by HaitongZhang** [comment]
Are u going to share some of the results of this project ? THX!

**Comment by vsimkus** [comment]
Took me much longer to find some spare time to do this, but I've added a very brief how-to guide in the readme. Hope it helps for those interested in extending this work or using it in their own projects.

@HaitongZhang Our results can be found in the [report file](https://github.com/vsimkus/voice-conversion/blob/master/report/report.pdf).
